import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/app/(components)/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-col h-screen max-h-screen">
        <Navigation/>
        <div className="flex-grow overflow-y-auto bg-accent-1 text-default-text">{children}</div>
      </div>
      </body>
    </html>
  );
}
